### ISSUE TITLE
一个视图中多个textField如何使用呢？

### ISSUE THREAD

**Issue by jiazufei** [liuzhiyi1992/ZYKeyboardUtil#1]
[_keyboardUtil setAnimateWhenKeyboardAppearAutomaticAnimBlock:^NSDictionary *{
        NSDictionary *adaptiveDict = [NSDictionary dictionaryWithObjectsAndKeys:weakSelf.mainTextField, ADAPTIVE_VIEW, weakSelf.view, CONTROLLER_VIEW, nil];
        return adaptiveDict;
    }];

**Comment by liuzhiyi1992** [comment]
<img width="416" alt="166a69d0-e6d1-4337-8ff3-e833392fb325" src="https://cloud.githubusercontent.com/assets/13046550/13870835/3a009be0-ed1a-11e5-830c-f066b71fdfce.png">

目前我也有使用两个textField的情况，因为textFied相邻，我的处理方法是将两个textField的superView(红框部分)当成ADAPTIVE_VIEW传入。

以后会尝试做多个textField的处理。谢谢支持。

ZYKeyboardUtil近期会整理更新，尝试将收键盘后的恢复动作也自动化。谢谢支持

**Comment by willingor** [comment]
确实挺好用的，就是一个视图中多个textField如何使用呢？

**Comment by liuzhiyi1992** [comment]
多个输入控件的问题会尽快抽时间给出答复，谢谢支持

**Comment by liuzhiyi1992** [comment]
ZYKeyboardUtil已更新0.4.1，支持多个textField，使用方式便捷性升级，一个Block自动处理键盘升降视图的变化和还原，详情请参考Demo。

使用可变数组方式接收多个输入控件托管：
[_keyboardUtil setAnimateWhenKeyboardAppearAutomaticAnimBlock:^(ZYKeyboardUtil *keyboardUtil) {
        [keyboardUtil adaptiveViewHandleWithController:weakSelf adaptiveView:weakSelf.inputViewBorderView, weakSelf.secondTextField, weakSelf.thirdTextField, nil];
    }];

谢谢大家继续支持！
