### ISSUE TITLE
无法用pod安装

### ISSUE THREAD

**Issue by disburden** [liuzhiyi1992/ZYKeyboardUtil#2]
[!] Unable to satisfy the following requirements:
- `ZYKeyboardUtil (~> 0.4.1)` required by `Podfile`

Specs satisfying the `ZYKeyboardUtil (~> 0.4.1)` dependency were found, but they required a higher minimum deployment target.

这是错误提示,求解

**Comment by liuzhiyi1992** [comment]
没有满足最低版本要求，ZYKeyboardUtil默认设置支持ios7.1以上，朋友的项目是否需要ios6起跳？
