### ISSUE TITLE
是否支持uitextview

### ISSUE THREAD

**Issue by taojigu** [liuzhiyi1992/ZYKeyboardUtil#3]
请问是否支持UITextView，并且在编辑时候，可以自动保证当前编辑行不被遮挡？

**Comment by liuzhiyi1992** [comment]
目前对UITextView的支持只是保证编辑时整个TextView不被遮挡

![simulator screen shot 2016 5 10 4 05 07](https://cloud.githubusercontent.com/assets/13046550/15139524/26d1ce94-16c9-11e6-8817-8035a9794d1a.png)

**Comment by liuzhiyi1992** [comment]
目前对UITextView的处理效果：
![](https://raw.githubusercontent.com/liuzhiyi1992/MyStore/master/ZYKeyboardUtil/ZYKeyboardUtil_TextView%E5%A4%84%E7%90%86%E6%BC%94%E7%A4%BA.gif)

@taojigu

**Comment by Lunaict** [comment]
UItextView scrollEnabled关闭 动态高度情况 可以处理吗？
