### ISSUE TITLE
键盘弹出和收回响应不是一般的慢

### ISSUE THREAD

**Issue by CookieJack** [liuzhiyi1992/ZYKeyboardUtil#4]
是真的慢，慢到用户都以为是卡机了。

**Comment by liuzhiyi1992** [comment]
是UITextField还是UITextView？可否用QuickTime录屏post到这里看看？以前没出过这种情况

是界面的适配响应慢还是键盘慢？可以参照下demo的正常情况

**Comment by CookieJack** [comment]
4S模拟器上很慢，就跟卡机似的。其他的型号还好，延迟没那么高。我不知道4S真机会不会也卡出翔。

**Comment by liuzhiyi1992** [comment]
对于朋友说的4S上卡顿的问题，刚才验证了下，真机和模拟器都没有出现类似问题，demo和我们公司的项目都尝试过了，对于朋友那边能不能猜测到时什么原因导致？

@CookieJack
