### ISSUE TITLE
影响导航栏

### ISSUE THREAD

**Issue by NengQuan** [liuzhiyi1992/ZYKeyboardUtil#9]
![img_1648](https://cloud.githubusercontent.com/assets/15306400/19505410/d57f589e-95f4-11e6-8c2f-0abe084ec078.PNG)

当进行键盘处理后 ，当前view默认从导航栏下方开始，不是从屏幕上方（0，0）开始，

**Comment by liuzhiyi1992** [comment]
已优化，不更新的话可以设置animateWhenKeyboardDisappearBlock，每当键盘收起时恢复界面的frame.

eg:

```
[_keyboardUtil setAnimateWhenKeyboardDisappearBlock:^(CGFloat keyboardHeight) {
        NSLog(@"\n\n键盘在收起来~  上次高度为:+%f", keyboardHeight);
        //do something
}];
```

**Comment by NengQuan** [comment]
en谢啦

**Comment by liuzhiyi1992** [comment]
不谢 :)
pod 出了点问题，今晚再更
